/**
 * OpenAPI 3.1 spec for PRISM's external API.
 *
 * Scope: only the public `/v1/*` namespace. The internal `/api/*` routes
 * (admin SPA, agent uploads, etc.) are intentionally NOT documented here
 * because they're not stable for third-party use.
 *
 * Served at GET /api/openapi.json (public, no auth required so external
 * developers can read it without provisioning a key).
 */

/**
 * Build the OpenAPI document. We accept a runtime `publicBaseUrl` so the
 * generated `servers[].url` can be overridden per deployment (prod / dev).
 */
export function buildOpenApi(publicBaseUrl: string): unknown {
  const BASE = (publicBaseUrl || '').replace(/\/+$/, '');
  const SERVER_URL = BASE + '/v1';
  // The Visualiser surface lives at `/api/visualiser/*`, not `/v1/visualiser/*`,
  // because it's the portal-contract API rather than the conversion API. We
  // describe it inside the same OpenAPI doc so a single spec covers both, and
  // we add a second `servers[]` entry so Redoc renders the absolute path
  // correctly. Phase K's narrative docs split this into a dedicated section.
  const API_BASE = BASE;

  return {
    openapi: '3.1.0',
    info: {
      title: 'PRISM API',
      version: '1.0.0',
      summary: 'CAD / mesh conversion + ORBIT object delivery as a service.',
      description: [
        'PRISM accepts CAD, mesh, and IFC files via HTTP, dispatches the conversion work',
        'to a pool of Rhino workstation agents, and uploads the resulting ORBIT objects',
        'to your configured ORBIT server — preserving native B-rep / SubD / Extrusion',
        'geometry through `RhinoDataObject.rawEncoding`.',
        '',
        'This page is the canonical integration reference.  See the table of contents on',
        'the right for endpoint-by-endpoint details.  The narrative sections below cover',
        '(in order) the supported formats, a copy-pasteable quickstart, authentication,',
        'rate limits, error shape, the two-phase layer-selection flow, additional output',
        'formats, and webhook delivery.',
        '',
        '## Supported file formats',
        '',
        'Uploads take one of two routes through the system.  Files Rhino can open',
        'directly are dispatched straight to a workstation agent.  Modern',
        'web/3D-DCC formats (`.gltf` / `.glb` / `.dae` / `.blend` / `.x` / `.usdz`)',
        'are first sent to the `prism-assimp` sidecar, which expands them into an',
        'OBJ + MTL + textures bundle that the agent then ingests as a normal',
        '`.zip` upload.  Either way the user-visible job row keeps the original',
        'filename and extension.',
        '',
        '| Format            | Status                            | Layer Selection                                       | Layer Colouring         | Texture Support                          | Bitmap Textures                                                                |',
        '| ----------------- | --------------------------------- | ----------------------------------------------------- | ----------------------- | ---------------------------------------- | ------------------------------------------------------------------------------ |',
        '| **3DM**           | Confirmed working                 | Supported                                             | **Supported**           | Supported                                | Supported                                                                      |',
        '| **DWG**           | Confirmed working                 | Supported                                             | **Supported**           | Partial — depends on origin software     | Supported if externally referenced                                             |',
        '| **DXF**           | Confirmed working                 | Supported                                             | **Supported**           | Partial — depends on origin software     | Supported if externally referenced                                             |',
        '| **FBX**           | Confirmed working                 | Supported                                             | Not supported           | Supported via `.zip` with textures       | Supported                                                                      |',
        '| **OBJ**           | Confirmed working                 | Partial — if layers are exported as OBJ groups        | Not supported           | Supported via `.zip` with textures       | Supported                                                                      |',
        '| **SKP**           | Confirmed working                 | Supported                                             | Not supported           | Partial support                          | Not supported                                                                  |',
        '| **STL**           | Confirmed working                 | Not supported                                         | Not supported           | Not supported                            | Not supported                                                                  |',
        '| **STEP** / **STP**| Confirmed working                 | Supported                                             | Not supported           | Layer colours imported as textures       | Not supported                                                                  |',
        '| **DAE**           | Confirmed working (Assimp)        | Supported — derived from COLLADA `<node name>`        | Not supported           | Supported via `.zip` with textures       | Supported                                                                      |',
        '| **GLB** / **GLTF**| Pre-convert via Assimp (untested) | Expected: supported (one OBJ group per glTF mesh)     | Not supported           | Supported via `.zip` with textures (PBR) | Supported (embedded in `.glb`, sibling files in `.gltf`)                       |',
        '| **3MF**           | Native Rhino import (untested)    | Expected: supported                                   | Unknown                 | Unknown                                  | Unknown                                                                        |',
        '| **IGES** / **IGS**| Native Rhino import (untested)    | Not supported (format has no layer concept)           | Object colours only     | Not supported                            | Not supported                                                                  |',
        '| **PLY**           | Native Rhino import (untested)    | Not supported                                         | Vertex colours only     | Not supported                            | Not supported                                                                  |',
        '| **BLEND**         | Pre-convert via Assimp (untested) | Expected: supported                                   | Not supported           | Supported via `.zip` with textures       | Supported                                                                      |',
        '| **X** (DirectX)   | Pre-convert via Assimp (untested) | Expected: supported                                   | Not supported           | Supported via `.zip` with textures       | Supported                                                                      |',
        '| **USDZ**          | Pre-convert via Assimp (untested) | Expected: supported                                   | Not supported           | Supported via `.zip` with textures       | Supported (embedded)                                                           |',
        '| **ZIP**           | Bundle wrapper                    | Inherited from primary file                           | Inherited               | Inherited                                | Inherited                                                                      |',
        '',
        '> Submit a `.zip` containing the primary geometry file plus any sibling',
        '> assets (textures, FBX media, glTF buffers) and the agent\'s',
        '> `ZipBundleExtractor` will pick the primary geometry automatically and',
        '> point Rhino\'s importer at the extracted directory so referenced',
        '> assets resolve.',
        '',
        '## Quickstart',
        '',
        'A round-trip from "I have a `.3dm` on disk" to "I have an ORBIT version URL"',
        'is three calls: submit, poll, done.',
        '',
        '### Single-shot convert (no layer picker)',
        '',
        '```bash',
        '# 1. Submit the file',
        'curl -sS -X POST https://prism.rebus.industries/v1/convert/async \\',
        '     -H "X-API-Key: $PRISM_KEY" \\',
        '     -F "file=@/path/to/model.3dm" \\',
        '     -F "projectId=$ORBIT_PROJECT_ID" \\',
        '     -F "modelId=$ORBIT_MODEL_ID"',
        '# -> {"jobId":"a1b2c3...","status":"queued"}',
        '',
        '# 2. Poll until terminal',
        'curl -sS https://prism.rebus.industries/v1/jobs/a1b2c3... \\',
        '     -H "X-API-Key: $PRISM_KEY"',
        '# -> {"status":"processing","progressPercent":42,...}',
        '# (later)',
        '# -> {"status":"complete","resultUrl":"https://orbit.rebus.industries/projects/.../models/...@..."}',
        '```',
        '',
        '### Same flow in TypeScript / Node',
        '',
        '```ts',
        'const PRISM = "https://prism.rebus.industries/v1";',
        'const KEY   = process.env.PRISM_KEY!;',
        '',
        'const fd = new FormData();',
        'fd.set("file",       new Blob([await readFile("model.3dm")]), "model.3dm");',
        'fd.set("projectId",  ORBIT_PROJECT_ID);',
        'fd.set("modelId",    ORBIT_MODEL_ID);',
        '',
        'const submit = await fetch(`${PRISM}/convert/async`, {',
        '  method:  "POST",',
        '  headers: { "X-API-Key": KEY },',
        '  body:    fd,',
        '});',
        'if (!submit.ok) throw new Error(`submit failed: ${submit.status} ${await submit.text()}`);',
        'const { jobId } = await submit.json();',
        '',
        '// Poll once a second until terminal',
        'while (true) {',
        '  const r = await fetch(`${PRISM}/jobs/${jobId}`, { headers: { "X-API-Key": KEY } });',
        '  const job = await r.json();',
        '  if (job.status === "complete") { console.log("ORBIT version:", job.resultUrl); break; }',
        '  if (job.status === "failed" || job.status === "cancelled") throw new Error(job.error);',
        '  await new Promise(r => setTimeout(r, 1000));',
        '}',
        '```',
        '',
        'Live progress can also be streamed over Server-Sent Events at',
        '`GET /jobs/{id}/stream` — see [Polling vs SSE](#section/Polling-vs-SSE) below.',
        '',
        '## Authentication',
        '',
        'All `/v1/*` endpoints require an API key supplied in the `X-API-Key` header.',
        'Mint keys in the admin UI under **API keys** (an admin must do this for you;',
        'we do not yet self-serve key issuance). Keep keys secret — they grant the',
        'ability to spend your monthly conversion quota.',
        '',
        '## Rate limits',
        '',
        'Every request is metered against the issuing key. Two policies apply:',
        '',
        '* **Per-minute rate limit** — short-burst protection (default 60/min, configurable per key).',
        '* **Monthly quota** — total conversion + receive jobs per calendar month.',
        '',
        'Both budgets are reported via response headers:',
        '',
        '* `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`',
        '* `X-Quota-Limit`, `X-Quota-Remaining`, `X-Quota-Reset`',
        '',
        'When exceeded, the API returns `429 Too Many Requests`.',
        '',
        '## Errors',
        '',
        'All errors return JSON of shape `{ "error": "<message>" }`. Validation errors',
        'additionally include `issues` (zod-formatted). HTTP status codes follow the',
        'usual semantics: `400` bad request, `401` missing/invalid key, `403` ownership',
        'mismatch, `404` not found, `415` unsupported media type, `429` rate-limited.',
        '',
        '## Two-phase layer selection',
        '',
        'Most user-facing portals want to let the user pick which Rhino layers to',
        'send to ORBIT.  PRISM supports this without uploading the file twice:',
        'add `selectLayers=true` to the original `POST /convert/async` and the',
        'job will pause in `awaiting_selection` after the agent reports the',
        'layer tree.  Submit the chosen layers on `POST /jobs/{id}/layers` to',
        'resume normal convert dispatch.',
        '',
        'Layer extraction quality is format-dependent — see the [Supported file',
        'formats](#section/Supported-file-formats) table\'s **Layer Selection**',
        'column.  Formats marked "Not supported" (STL, IGES, PLY) will return a',
        'single root layer; calling `selectLayers=true` on those is harmless but',
        'pointless.',
        '',
        '### Job lifecycle',
        '',
        '```',
        '  caller       PRISM server          layering agent       convert agent',
        '    │   POST /convert/async   │',
        '    │  (selectLayers=true)    │',
        '    │ ───────────────────────▶│ → queued',
        '    │                         │  pollLayers ──▶ ┌──────────────┐',
        '    │  202 { jobId }          │                 │ open file    │',
        '    │ ◀───────────────────────│                 │ walk layers  │',
        '    │                         │ ◀───── layers   └──────────────┘',
        '    │                         │ → awaiting_selection',
        '    │  GET /jobs/{id}/layers  │',
        '    │ ───────────────────────▶│',
        '    │  200 { layers: […] }    │',
        '    │ ◀───────────────────────│',
        '    │  POST /jobs/{id}/layers │',
        '    │   { includedLayers… }   │',
        '    │ ───────────────────────▶│ → queued',
        '    │                         │  assign ─────────────────▶ ┌──────────────┐',
        '    │                         │                            │ convert      │',
        '    │                         │ ◀────── progress (×n) ───  │ upload       │',
        '    │                         │ ◀────── complete ────────  └──────────────┘',
        '    │                         │ → complete',
        '```',
        '',
        '### End-to-end TypeScript example',
        '',
        '```ts',
        'const PRISM = "https://prism.rebus.industries/v1";',
        'const KEY   = process.env.PRISM_KEY!;',
        '',
        '// 1. Submit with selectLayers=true',
        'const fd = new FormData();',
        'fd.set("file",          new Blob([await readFile("model.3dm")]), "model.3dm");',
        'fd.set("projectId",     ORBIT_PROJECT_ID);',
        'fd.set("modelId",       ORBIT_MODEL_ID);',
        'fd.set("selectLayers",  "true");',
        '',
        'const submit = await fetch(`${PRISM}/convert/async`, {',
        '  method:  "POST",',
        '  headers: { "X-API-Key": KEY },',
        '  body:    fd,',
        '});',
        'const { jobId } = await submit.json();',
        '',
        '// 2. Wait for the layer tree.  The agent returns it within a few seconds for',
        '//    most files.  Poll /layers (the simplest option) or subscribe to /stream',
        '//    if you want to render progress while waiting.',
        'let layers;',
        'while (true) {',
        '  const r = await fetch(`${PRISM}/jobs/${jobId}/layers`, { headers: { "X-API-Key": KEY } });',
        '  if (r.ok) { ({ layers } = await r.json()); break; }',
        '  if (r.status !== 404) throw new Error(`layers fetch failed: ${r.status}`);',
        '  await new Promise(r => setTimeout(r, 750));',
        '}',
        '',
        '// 3. Show `layers` (a recursive tree of {name, fullPath, color, visible, children})',
        '//    in your UI.  When the user clicks "Convert", POST their picks back.',
        'const chosen = ["Default", "Walls", "Walls::Internal"];',
        'await fetch(`${PRISM}/jobs/${jobId}/layers`, {',
        '  method:  "POST",',
        '  headers: { "X-API-Key": KEY, "Content-Type": "application/json" },',
        '  body:    JSON.stringify({',
        '    includedLayers:          chosen,',
        '    includeLayerDescendants: true,   // optional: also include sub-layers',
        '  }),',
        '});',
        '',
        '// 4. Resume polling /jobs/{id} as in the quickstart until status === "complete".',
        '```',
        '',
        '### Layer tree shape',
        '',
        'The `GET /jobs/{id}/layers` response and the `layers` field of the SSE',
        '`update` frame both use the same recursive `LayerNode` schema:',
        '',
        '```jsonc',
        '{',
        '  "jobId":  "a1b2c3...",',
        '  "status": "awaiting_selection",',
        '  "layers": [',
        '    {',
        '      "name":     "Walls",',
        '      "fullPath": "Walls",        // top-level layers have name == fullPath',
        '      "color":    "#ff8800",',
        '      "visible":  true,',
        '      "children": [',
        '        { "name": "Internal", "fullPath": "Walls::Internal", "color": "#aa6600", "visible": true, "children": [] },',
        '        { "name": "External", "fullPath": "Walls::External", "color": "#882200", "visible": false, "children": [] }',
        '      ]',
        '    }',
        '  ],',
        '  "includedLayers":          [],',
        '  "includeLayerDescendants": false',
        '}',
        '```',
        '',
        'Send the **`fullPath`** strings (Rhino layer paths joined with `" :: "`)',
        'when posting your selection, not the `name` strings — names can collide',
        'across different parents.  Set `includeLayerDescendants=true` when the',
        'user picks a parent and you want every sub-layer included automatically.',
        '',
        '### Skipping the picker entirely',
        '',
        'If the caller already knows which layer paths it wants (e.g. an automation',
        'that always sends "Architecture::Walls" + "Architecture::Slabs"), pass',
        '`includedLayers` (CSV) on the original `/convert/async` call and *leave',
        '`selectLayers` unset*.  The job dispatches straight to convert without the',
        'layering hop.',
        '',
        '```bash',
        'curl -X POST https://prism.rebus.industries/v1/convert/async \\',
        '     -H "X-API-Key: $PRISM_KEY" \\',
        '     -F "file=@/path/to/model.3dm" \\',
        '     -F "projectId=$ORBIT_PROJECT_ID" \\',
        '     -F "modelId=$ORBIT_MODEL_ID" \\',
        '     -F "includedLayers=Architecture::Walls,Architecture::Slabs" \\',
        '     -F "includeLayerDescendants=true"',
        '```',
        '',
        '## Polling vs SSE',
        '',
        'Two ways to track a job after submission:',
        '',
        '* **Poll `GET /jobs/{id}` every 1-2 s** — simplest, works through any',
        '  proxy, no special headers required.  Stop when `status` is one of',
        '  `complete`, `failed`, `cancelled`.',
        '* **Subscribe to `GET /jobs/{id}/stream`** — Server-Sent Events.',
        '  First frame is `event: state` (the full job record); every subsequent',
        '  agent update arrives as `event: update`.  Lower latency, lower load on',
        '  PRISM, and the `awaiting_selection` frame includes the `layers` tree',
        '  inline so you can skip the explicit `GET /jobs/{id}/layers` round-trip.',
        '  Close the connection when you observe a terminal status.',
        '',
        '```ts',
        '// Browser-style SSE example.',
        'const es = new EventSource(`${PRISM}/jobs/${jobId}/stream`, { withCredentials: false });',
        'es.addEventListener("state",  e => console.log("init:",   JSON.parse((e as MessageEvent).data)));',
        'es.addEventListener("update", e => {',
        '  const job = JSON.parse((e as MessageEvent).data);',
        '  if (job.status === "awaiting_selection") {',
        '    showLayerPicker(job.layers);  // delivered inline — no extra fetch needed',
        '  } else if (["complete", "failed", "cancelled"].includes(job.status)) {',
        '    es.close();',
        '  }',
        '});',
        '```',
        '',
        '> Note: `EventSource` cannot send `X-API-Key` headers.  In a server-side',
        '> integration use `fetch` with `Accept: text/event-stream` and parse the',
        '> stream manually; in a browser context proxy the request through your',
        '> own backend so the key never leaves your servers.',
        '',
        '## Additional output formats',
        '',
        'A convert job always uploads its result to ORBIT (you get back',
        '`resultUrl` + `versionId` on completion).  Pass `outputFormats` (CSV) on',
        '`POST /convert/async` to *also* render the model into one or more flat',
        'files that PRISM stores for download:',
        '',
        '| Code   | Description                                              |',
        '| ------ | -------------------------------------------------------- |',
        '| `3dm`  | Native Rhino document — round-trips B-rep / SubD losslessly. |',
        '| `step` | ISO 10303-21 STEP — interoperable B-rep for downstream CAD.  |',
        '| `glb`  | Binary glTF 2.0 — for web viewers / WebGL preview.       |',
        '| `ifc`  | Industry Foundation Classes — building-data exchange.    |',
        '',
        'When the job completes, the URLs land on `job.outputs.<format>` and are',
        'separately downloadable via `GET /jobs/{id}/outputs/{format}`.  The',
        'binary stream is `application/octet-stream`; pick a filename based on the',
        'job\'s original `fileName` + the format extension.',
        '',
        '```bash',
        'curl -X POST https://prism.rebus.industries/v1/convert/async \\',
        '     -H "X-API-Key: $PRISM_KEY" \\',
        '     -F "file=@/path/to/model.3dm" \\',
        '     -F "projectId=$ORBIT_PROJECT_ID" \\',
        '     -F "modelId=$ORBIT_MODEL_ID" \\',
        '     -F "outputFormats=glb,step"',
        '# later, after status=complete:',
        'curl -OJ https://prism.rebus.industries/v1/jobs/a1b2c3.../outputs/glb \\',
        '     -H "X-API-Key: $PRISM_KEY"',
        '```',
        '',
        '## Webhooks',
        '',
        'You can register a webhook URL in the admin UI and PRISM will POST',
        '`job.complete` and `job.failed` events to it. The body is signed with',
        'HMAC-SHA256 over the raw request bytes — see `GET /webhooks/signature-spec`',
        'for the canonical signing details.',
      ].join('\n'),
      contact: {
        name: 'REBUS-ORBIT',
        url: 'https://github.com/REBUS-ORBIT/prism',
      },
      license: { name: 'Proprietary — Rebus Industries' },
    },
    servers: [
      { url: SERVER_URL, description: 'Production — /v1 conversion + receive surface' },
      { url: API_BASE,   description: 'Production root — used by /api/visualiser/* portal surface' },
    ],

    tags: [
      { name: 'Meta',       description: 'Health and metadata.' },
      { name: 'Convert',    description: 'Submit a file for conversion to ORBIT.' },
      { name: 'Receive',    description: 'Materialise an ORBIT version into a downloadable file (.3dm or .step).' },
      { name: 'Jobs',       description: 'Poll job status and download outputs.' },
      { name: 'Visualiser', description: 'Start, poll, and stop Pixel Streaming sessions of ORBIT versions. Portal-facing — see [Authentication](#section/Authentication) for the `visualiser:create_stream` scope requirement.' },
      { name: 'Webhooks',   description: 'Inspect webhook signature contract.' },
    ],

    security: [{ apiKey: [] }],

    components: {
      securitySchemes: {
        apiKey: {
          type: 'apiKey',
          in: 'header',
          name: 'X-API-Key',
          description: 'Plaintext API key minted in the PRISM admin UI. Format: `prism_<base64url>`.',
        },
      },
      headers: {
        'X-RateLimit-Limit':     { description: 'Per-minute request budget for the key.',     schema: { type: 'integer' } },
        'X-RateLimit-Remaining': { description: 'Requests remaining in the current minute.',  schema: { type: 'integer' } },
        'X-RateLimit-Reset':     { description: 'Unix epoch seconds when the bucket resets.', schema: { type: 'integer' } },
        'X-Quota-Limit':         { description: 'Monthly job-submission quota for the key.',  schema: { type: 'integer' } },
        'X-Quota-Remaining':     { description: 'Quota remaining for this calendar month.',   schema: { type: 'integer' } },
        'X-Quota-Reset':         { description: 'Unix epoch seconds when the quota resets.',  schema: { type: 'integer' } },
      },
      schemas: {
        Error: {
          type: 'object',
          required: ['error'],
          properties: {
            error:  { type: 'string', example: 'unsupported format: .xyz' },
            issues: { type: 'array', items: { type: 'object' }, description: 'Optional zod validation issues.' },
          },
        },
        JobStatus: {
          type: 'string',
          enum: ['queued', 'dispatched', 'awaiting_selection', 'processing', 'uploading', 'complete', 'failed', 'cancelled'],
          description: [
            'Job lifecycle:',
            '* `queued` — job persisted, awaiting dispatch.',
            '* `dispatched` — sent to an agent (convert OR pollLayers — see `currentStage`).',
            '* `awaiting_selection` — two-phase flow only: agent returned the layer tree;',
            '  POST `/jobs/{id}/layers` with your selection to resume.',
            '* `processing` — agent is converting.',
            '* `uploading` — agent is uploading to ORBIT / non-ORBIT outputs.',
            '* `complete` / `failed` / `cancelled` — terminal.',
          ].join('\n'),
        },
        LayerNode: {
          type: 'object',
          required: ['name'],
          properties: {
            name:     { type: 'string', description: 'Layer display name.' },
            fullPath: { type: 'string', description: 'Rhino layer full path (parents joined with " :: ").' },
            color:    { type: 'string', description: 'Layer display colour as #rrggbb hex.' },
            visible:  { type: 'boolean', description: 'True when the layer is visible AND unlocked.' },
            children: { type: 'array', items: { $ref: '#/components/schemas/LayerNode' } },
          },
        },
        LayersResponse: {
          type: 'object',
          required: ['jobId', 'status', 'layers'],
          properties: {
            jobId:                   { type: 'string', format: 'uuid' },
            status:                  { $ref: '#/components/schemas/JobStatus' },
            layers:                  { type: 'array', items: { $ref: '#/components/schemas/LayerNode' } },
            includedLayers:          { type: 'array', items: { type: 'string' } },
            includeLayerDescendants: { type: 'boolean' },
          },
        },
        LayerSelection: {
          type: 'object',
          required: ['includedLayers'],
          properties: {
            includedLayers:          { type: 'array', items: { type: 'string' }, description: 'List of layer `fullPath` strings to include.' },
            includeLayerDescendants: { type: 'boolean', default: false, description: 'Auto-include every descendant of each selected layer.' },
          },
        },
        JobKind: {
          type: 'string',
          enum: ['convert', 'receive'],
        },
        Job: {
          type: 'object',
          properties: {
            id:               { type: 'string', format: 'uuid' },
            status:           { $ref: '#/components/schemas/JobStatus' },
            jobType:          { $ref: '#/components/schemas/JobKind' },
            createdAt:        { type: 'string', format: 'date-time' },
            updatedAt:        { type: 'string', format: 'date-time' },
            completedAt:      { type: 'string', format: 'date-time', nullable: true },
            fileName:         { type: 'string' },
            fileSize:         { type: 'integer' },
            format:           { type: 'string', example: '.3dm' },
            orbitTarget:      { type: 'string', enum: ['prod', 'dev'] },
            projectId:        { type: 'string' },
            modelId:          { type: 'string' },
            modelName:        { type: 'string', nullable: true },
            currentStage:     { type: 'string', nullable: true,
                                example: 'meshing',
                                description: 'Current agent-side pipeline node.' },
            progressPercent:  { type: 'integer', nullable: true, minimum: 0, maximum: 100 },
            lastMessage:      { type: 'string', nullable: true },
            resultUrl:        { type: 'string', nullable: true, description: 'Deep link to the resulting ORBIT version (for convert jobs).' },
            versionId:        { type: 'string', nullable: true, description: 'ORBIT version id produced by a convert job.' },
            rootObjectId:     { type: 'string', nullable: true },
            outputs:          { type: 'object',
                                additionalProperties: { type: 'string', format: 'uri' },
                                nullable: true,
                                description: 'For convert jobs that requested extra outputs (3dm, step, glb, ifc) this maps format -> downloadable URL.' },
            receiveVersionId: { type: 'string', nullable: true, description: 'For receive jobs: the ORBIT version that was materialised.' },
            error:            { type: 'string', nullable: true },
          },
        },
        JobAccepted: {
          type: 'object',
          required: ['jobId', 'status'],
          properties: {
            jobId:  { type: 'string', format: 'uuid' },
            status: { type: 'string', example: 'queued' },
          },
        },
        WebhookSignatureSpec: {
          type: 'object',
          properties: {
            header:    { type: 'string', example: 'x-prism-signature' },
            algorithm: { type: 'string', example: 'HMAC-SHA256' },
            encoding:  { type: 'string', example: 'sha256=<hex>' },
            payload:   { type: 'string', example: 'raw request body bytes' },
          },
        },
        VisualiserStatus: {
          type: 'string',
          enum: ['queued', 'importing', 'streaming', 'failed', 'ended'],
          description: [
            '* `queued`    — row created; dispatcher not yet picked a workstation.',
            '* `importing` — dispatched; agent is materialising the ORBIT version into UE.',
            '* `streaming` — orchestrator handed back a ready event; signallingUrl is live.',
            '* `failed`    — terminal (agent failed, start_timeout, no workstation, etc).',
            '* `ended`     — terminal (admin cancel, TTL expired, UE exited, browser disconnect).',
          ].join('\n'),
        },
        VisualiserTurnBundle: {
          type: 'object',
          description: 'RFC 7635 long-term credential bundle for coturn. `null` if the server has not been configured with `TURN_SECRET` yet (Phase H wires it).',
          nullable: true,
          properties: {
            urls:       { type: 'array', items: { type: 'string', example: 'turn:visualiser.rebus.industries:3478' } },
            username:   { type: 'string', example: '1748284800:5b9c1d4f' },
            credential: { type: 'string', example: 'gHrjK0i…' },
            ttl:        { type: 'integer', example: 86400 },
          },
        },
        VisualiserStartRequest: {
          type: 'object',
          required: ['projectId', 'modelId'],
          properties: {
            projectId:             { type: 'string', description: 'ORBIT project id.' },
            modelId:               { type: 'string', description: 'ORBIT model id.' },
            versionId:             { type: 'string', description: 'ORBIT version id. Omit to materialise the model\'s latest version.' },
            orbitTarget:           { type: 'string', enum: ['prod', 'dev'], default: 'prod' },
            preferredWorkstationId:{ type: 'string', format: 'uuid', description: 'Reserved — the dispatcher currently picks the least-loaded eligible workstation.' },
            callbackUrl:           { type: 'string', format: 'uri', description: 'Reserved — Phase G accepts but does not yet POST to this URL.' },
            templateTag:           { type: 'string', description: 'Pin the UE template tag the agent runs against (e.g. `v1.0.0-ue5.7`).' },
            ttlSeconds:            { type: 'integer', minimum: 1, description: 'Hard tear-down deadline enforced by the orchestrator.' },
          },
        },
        VisualiserReadyResponse: {
          type: 'object',
          required: ['schema', 'runId', 'status', 'signallingUrl', 'playerUrl'],
          properties: {
            schema:        { type: 'string', example: 'prism-visualiser/ready/v1' },
            runId:         { type: 'string', format: 'uuid' },
            status:        { type: 'string', enum: ['streaming'] },
            signallingUrl: { type: 'string', example: 'wss://prism.rebus.industries/ws/visualiser/<runId>/signalling' },
            playerUrl:     { type: 'string', example: 'https://prism.rebus.industries/admin/#/visualiser/<runId>' },
            streamerId:    { type: 'string', example: 'orbit_5b9c1d4f' },
            turn:          { $ref: '#/components/schemas/VisualiserTurnBundle' },
          },
        },
        VisualiserFailedResponse: {
          type: 'object',
          required: ['schema', 'runId', 'error', 'code', 'message'],
          properties: {
            schema:  { type: 'string', example: 'prism-visualiser/failed/v1' },
            runId:   { type: 'string', format: 'uuid' },
            error:   { type: 'string', example: 'visualisation_failed' },
            code:    { type: 'string', example: 'start_timeout',
                       description: 'Machine-readable failure code: `no_workstation_available` | `all_workstations_busy` | `agent_failed` | `start_timeout` | `misconfigured` | `agent_send_failed`.' },
            message: { type: 'string', example: 'start exceeded 180000ms' },
          },
        },
        VisualiserRun: {
          type: 'object',
          required: ['id', 'status', 'projectId', 'modelId', 'createdAt'],
          properties: {
            id:                  { type: 'string', format: 'uuid' },
            status:              { $ref: '#/components/schemas/VisualiserStatus' },
            orbitTarget:         { type: 'string', enum: ['prod', 'dev'] },
            projectId:           { type: 'string' },
            modelId:             { type: 'string' },
            versionId:           { type: 'string', nullable: true },
            templateTag:         { type: 'string', nullable: true },
            workstationId:       { type: 'string', format: 'uuid', nullable: true },
            agentSessionId:      { type: 'string', format: 'uuid', nullable: true },
            signallingUrl:       { type: 'string', nullable: true },
            playerUrl:           { type: 'string', nullable: true },
            streamerId:          { type: 'string', nullable: true },
            failureReason:       { type: 'string', nullable: true },
            error:               { type: 'string', nullable: true },
            ttlSeconds:          { type: 'integer', nullable: true },
            submittedBy:         { type: 'string', nullable: true },
            requestedByApiKeyId: { type: 'string', format: 'uuid', nullable: true },
            createdAt:           { type: 'string', format: 'date-time' },
            updatedAt:           { type: 'string', format: 'date-time' },
            dispatchedAt:        { type: 'string', format: 'date-time', nullable: true },
            readyAt:             { type: 'string', format: 'date-time', nullable: true },
            endedAt:             { type: 'string', format: 'date-time', nullable: true },
          },
        },
        VisualiserSignallingToken: {
          type: 'object',
          required: ['token', 'exp'],
          properties: {
            token: { type: 'string', description: 'HS256 JWT. Append as `?token=…` to the signalling WS URL.' },
            exp:   { type: 'integer', description: 'Token expiry, Unix epoch seconds.' },
          },
        },
      },
      responses: {
        Unauthorized: {
          description: 'Missing or invalid API key.',
          content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
        },
        Forbidden: {
          description: 'The job belongs to a different API key.',
          content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
        },
        NotFound: {
          description: 'Resource not found.',
          content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
        },
        RateLimited: {
          description: 'Rate limit or monthly quota exceeded.',
          headers: {
            'X-RateLimit-Reset': { $ref: '#/components/headers/X-RateLimit-Reset' },
            'X-Quota-Reset':     { $ref: '#/components/headers/X-Quota-Reset' },
          },
          content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
        },
      },
    },

    paths: {
      '/health': {
        get: {
          tags: ['Meta'],
          summary: 'Liveness probe',
          description: 'Returns 200 if the API surface is reachable with a valid key.',
          security: [{ apiKey: [] }],
          responses: {
            '200': {
              description: 'OK',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: { status: { type: 'string', example: 'ok' }, api: { type: 'string', example: 'v1' } },
                  },
                },
              },
            },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '429': { $ref: '#/components/responses/RateLimited' },
          },
        },
      },

      '/convert/async': {
        post: {
          tags: ['Convert'],
          summary: 'Submit a file for conversion -> ORBIT',
          description: [
            'Upload a CAD / mesh / IFC file.  The full list of accepted',
            'extensions and which capabilities each format supports lives in',
            '[Supported file formats](#section/Supported-file-formats).  In',
            'short: every Rhino-native format (3dm, dwg, dxf, fbx, obj, stl,',
            'ply, 3mf, skp, step/stp, iges/igs) plus the Assimp-bridged',
            'web/3D-DCC family (gltf, glb, dae, blend, x, usdz), with `.zip`',
            'as the bundle wrapper for files that reference external assets',
            '(textures, MTL, glTF buffers).',
            '',
            'The response contains a `jobId` you can poll via `GET /jobs/{jobId}`',
            'or stream over Server-Sent Events at `GET /jobs/{jobId}/stream` —',
            'see [Polling vs SSE](#section/Polling-vs-SSE).',
            '',
            'On success the job\'s `status` advances to `complete` and `resultUrl`',
            'points at the resulting ORBIT version.  Set `outputFormats=glb,step`',
            'to additionally render those formats — see [Additional output',
            'formats](#section/Additional-output-formats).',
            '',
            'For a layer-picker UX, set `selectLayers=true` and follow the',
            '[Two-phase layer selection](#section/Two-phase-layer-selection)',
            'flow.  Callers that already know the layer paths can submit them',
            'directly via `includedLayers` and skip the picker entirely.',
          ].join('\n'),
          requestBody: {
            required: true,
            content: {
              'multipart/form-data': {
                schema: {
                  type: 'object',
                  required: ['file', 'projectId', 'modelId'],
                  properties: {
                    file:       { type: 'string', format: 'binary', description: 'The source file. <=1 GB.' },
                    projectId:  { type: 'string', description: 'ORBIT project id.' },
                    modelId:    { type: 'string', description: 'ORBIT model id.' },
                    modelName:  { type: 'string' },
                    orbitTarget:{ type: 'string', enum: ['prod', 'dev'], default: 'prod' },
                    swapYZ:     { type: 'boolean', default: false, description: 'Swap Y and Z axes during import (CAD ↔ DCC handedness).' },
                    quality:    { type: 'string', enum: ['sensible', 'extreme'], default: 'sensible' },
                    callbackUrl:{ type: 'string', format: 'uri', description: 'Optional webhook URL to POST a `job.complete` / `job.failed` event to (in addition to globally configured webhooks).' },
                    outputFormats: { type: 'string', description: 'Comma-separated list of additional output formats (`3dm, step, glb, ifc`). Each format is rendered and uploaded; downloadable via `GET /jobs/{id}/outputs/{format}`.' },
                    includedLayers: { type: 'string', description: 'Comma-separated layer `fullPath` strings to include (others are skipped). Use the two-phase flow (`selectLayers=true`) if you don\'t know the layer paths up front.' },
                    includeLayerDescendants: { type: 'boolean', default: false, description: 'When `includedLayers` is set, also include every descendant of each listed layer.' },
                    selectLayers: { type: 'boolean', default: false, description: 'Two-phase flow: when true, PRISM first dispatches a `pollLayers` job to a layering-capable agent which returns the file\'s layer tree. The job lands in `awaiting_selection`; poll `GET /jobs/{id}/layers` for the tree, then `POST /jobs/{id}/layers` with your selection to resume normal convert dispatch.' },
                  },
                },
              },
            },
          },
          responses: {
            '202': {
              description: 'Job accepted and queued.',
              content: { 'application/json': { schema: { $ref: '#/components/schemas/JobAccepted' } } },
            },
            '400': { description: 'Validation failed.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '415': { description: 'Unsupported file extension.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '429': { $ref: '#/components/responses/RateLimited' },
          },
        },
      },

      '/receive/async': {
        post: {
          tags: ['Receive'],
          summary: 'Materialise an ORBIT version into a downloadable file',
          description: [
            'Asks an agent to download an existing ORBIT version into a Rhino doc',
            'and re-export it as a single file (`3dm` or `step`). Useful when an',
            'external system needs a flat file copy of an ORBIT model snapshot.',
            '',
            'Poll `GET /jobs/{jobId}` until `status=complete`, then download via',
            '`GET /jobs/{jobId}/outputs/{format}`.',
          ].join('\n'),
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  required: ['projectId', 'modelId', 'versionId'],
                  properties: {
                    projectId:  { type: 'string' },
                    modelId:    { type: 'string' },
                    versionId:  { type: 'string' },
                    modelName:  { type: 'string' },
                    orbitTarget:{ type: 'string', enum: ['prod', 'dev'], default: 'prod' },
                    outputFormat:{ type: 'string', enum: ['3dm', 'step'], default: '3dm' },
                    callbackUrl:{ type: 'string', format: 'uri' },
                  },
                },
              },
            },
          },
          responses: {
            '202': {
              description: 'Job accepted and queued.',
              content: { 'application/json': { schema: { $ref: '#/components/schemas/JobAccepted' } } },
            },
            '400': { description: 'Validation failed.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '429': { $ref: '#/components/responses/RateLimited' },
          },
        },
      },

      '/jobs/{id}': {
        get: {
          tags: ['Jobs'],
          summary: 'Poll job status',
          description: 'Returns the full job record. The `status` field is the primary signal; treat `complete`, `failed`, and `cancelled` as terminal.',
          parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string', format: 'uuid' } }],
          responses: {
            '200': { description: 'Current job state.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '403': { $ref: '#/components/responses/Forbidden' },
            '404': { $ref: '#/components/responses/NotFound' },
            '429': { $ref: '#/components/responses/RateLimited' },
          },
        },
      },

      '/jobs/{id}/stream': {
        get: {
          tags: ['Jobs'],
          summary: 'Stream live job progress via Server-Sent Events',
          description: [
            'Returns an `text/event-stream` connection. Each frame is one of:',
            '',
            '* `event: state` — initial snapshot of the job record (single frame at connect time).',
            '* `event: update` — subsequent partial updates (progress %, stage, message, status transitions).',
            '',
            'Close the connection once you see a terminal status (`complete`, `failed`, `cancelled`).',
          ].join('\n'),
          parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string', format: 'uuid' } }],
          responses: {
            '200': {
              description: 'SSE stream opened.',
              content: { 'text/event-stream': { schema: { type: 'string', example: 'event: update\ndata: {"progressPercent":42,"currentStage":"meshing"}\n\n' } } },
            },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '404': { $ref: '#/components/responses/NotFound' },
          },
        },
      },

      '/jobs/{id}/layers': {
        get: {
          tags: ['Jobs'],
          summary: 'Read the layer tree (two-phase flow)',
          description: [
            'For jobs submitted with `selectLayers=true`, this returns the layer tree',
            'the agent extracted from the uploaded file. The job sits in',
            '`awaiting_selection` until you POST the chosen layers back.',
            '',
            'Returns `404` (with `status` and `selectLayers` in the body) until the',
            'agent has replied with the tree. Poll this endpoint, or — preferred —',
            'subscribe to `/jobs/{id}/stream` and listen for the SSE `update`',
            'frame that delivers `status: awaiting_selection` with `layers` inline.',
          ].join('\n'),
          parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string', format: 'uuid' } }],
          responses: {
            '200': { description: 'Layer tree available.',
                     content: { 'application/json': { schema: { $ref: '#/components/schemas/LayersResponse' } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '403': { $ref: '#/components/responses/Forbidden' },
            '404': { description: 'Job not found OR layers not available yet (still polling agent).',
                     content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          },
        },
        post: {
          tags: ['Jobs'],
          summary: 'Submit layer selection (two-phase flow)',
          description: [
            'Re-queues a job from `awaiting_selection` back to `queued` so it gets',
            'dispatched as a regular convert with your chosen layers. Returns `409`',
            'if the job is in any other state.',
            '',
            'After this call, watch the existing `/jobs/{id}/stream` SSE channel',
            'for the normal `dispatched → processing → complete` progression.',
          ].join('\n'),
          parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string', format: 'uuid' } }],
          requestBody: {
            required: true,
            content: { 'application/json': { schema: { $ref: '#/components/schemas/LayerSelection' } } },
          },
          responses: {
            '200': {
              description: 'Selection persisted; job re-queued.',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: {
                      jobId: { type: 'string', format: 'uuid' },
                      status: { $ref: '#/components/schemas/JobStatus' },
                      includedLayers: { type: 'array', items: { type: 'string' } },
                      includeLayerDescendants: { type: 'boolean' },
                    },
                  },
                },
              },
            },
            '400': { description: 'Invalid body.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '403': { $ref: '#/components/responses/Forbidden' },
            '404': { $ref: '#/components/responses/NotFound' },
            '409': { description: 'Job is not in `awaiting_selection` state.',
                     content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          },
        },
      },

      '/jobs/{id}/outputs/{format}': {
        get: {
          tags: ['Jobs'],
          summary: 'Download a generated output file',
          description: 'For convert jobs that requested `outputFormats`, this streams the rendered file as `application/octet-stream`.',
          parameters: [
            { in: 'path', name: 'id',     required: true, schema: { type: 'string', format: 'uuid' } },
            { in: 'path', name: 'format', required: true, schema: { type: 'string', enum: ['3dm', 'step', 'ifc', 'glb'] } },
          ],
          responses: {
            '200': { description: 'Binary file.',
                     content: { 'application/octet-stream': { schema: { type: 'string', format: 'binary' } } } },
            '400': { description: 'Unknown format.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '403': { $ref: '#/components/responses/Forbidden' },
            '404': { description: 'Job not found, or output for this format has not been produced.',
                     content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          },
        },
      },

      '/webhooks/signature-spec': {
        get: {
          tags: ['Webhooks'],
          summary: 'Inspect the webhook signature contract',
          description: 'Returns the header name, algorithm, encoding, and payload definition that PRISM uses when signing webhook POST bodies. Use this to implement signature verification on your receiver.',
          responses: {
            '200': {
              description: 'Signing spec.',
              content: { 'application/json': { schema: { $ref: '#/components/schemas/WebhookSignatureSpec' } } },
            },
            '401': { $ref: '#/components/responses/Unauthorized' },
          },
        },
      },

      // -------------------------------------------------------------------- Visualiser
      //
      // Portal-facing Pixel Streaming surface. Unlike the rest of this spec
      // these endpoints live at `/api/visualiser/*` rather than `/v1/*` —
      // see the second `servers[]` entry. The Phase G implementation
      // requires `visualiser:create_stream` scope on the issuing API key
      // for POST; admin sessions bypass scope checks.
      '/api/visualiser/streams': {
        servers: [{ url: API_BASE }],
        post: {
          tags: ['Visualiser'],
          summary: 'Start a Pixel Streaming session',
          description: [
            'Synchronous. Blocks until the agent either reports the run is',
            'streaming (`prism-visualiser/ready/v1`), a terminal failure',
            '(`prism-visualiser/failed/v1`), or the deadline configured by',
            '`VISUALISER_START_TIMEOUT_MS` fires (default 180s).',
            '',
            '**Auth:** `X-API-Key` with the `visualiser:create_stream` scope,',
            'or an authenticated admin session.',
            '',
            'Warm round-trip is typically ~2-3 s; cold start (UE Editor warm-up + import) is ~60-90 s.',
          ].join('\n'),
          security: [{ apiKey: [] }],
          requestBody: {
            required: true,
            content: { 'application/json': { schema: { $ref: '#/components/schemas/VisualiserStartRequest' },
              examples: {
                latestVersion: {
                  summary: 'Start a stream against the latest version',
                  value: { projectId: 'cf900606f5', modelId: 'be45d33eb1' },
                },
                pinnedVersion: {
                  summary: 'Pin to a specific ORBIT version + UE template',
                  value: { projectId: 'cf900606f5', modelId: 'be45d33eb1', versionId: 'v_2026_05_12_001', templateTag: 'v1.0.0-ue5.7' },
                },
              },
            } },
          },
          responses: {
            '200': {
              description: 'Ready — the signallingUrl is live and the browser can connect.',
              content: { 'application/json': { schema: { $ref: '#/components/schemas/VisualiserReadyResponse' },
                example: {
                  schema: 'prism-visualiser/ready/v1',
                  runId: '5b9c1d4f-9d72-4a8c-8e64-7e22b5f2f01b',
                  status: 'streaming',
                  signallingUrl: 'wss://prism.rebus.industries/ws/visualiser/5b9c1d4f-9d72-4a8c-8e64-7e22b5f2f01b/signalling',
                  playerUrl:     'https://prism.rebus.industries/admin/#/visualiser/5b9c1d4f-9d72-4a8c-8e64-7e22b5f2f01b',
                  streamerId:    'orbit_5b9c1d4f',
                  turn: {
                    urls: ['turn:visualiser.rebus.industries:3478', 'turns:visualiser.rebus.industries:5349'],
                    username: '1748284800:5b9c1d4f',
                    credential: 'gHrjK0iA…',
                    ttl: 86400,
                  },
                },
              } },
            },
            '400': { description: 'Validation failed.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '403': { description: 'Missing `visualiser:create_stream` scope on the API key.',
                     content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '500': { description: 'Server is misconfigured (no ORBIT URL etc.).',
                     content: { 'application/json': { schema: { $ref: '#/components/schemas/VisualiserFailedResponse' } } } },
            '502': { description: 'Agent reported `visualisationFailed` during the start round-trip.',
                     content: { 'application/json': { schema: { $ref: '#/components/schemas/VisualiserFailedResponse' } } } },
            '503': { description: 'No workstation is online with `can_visualise`, or all are at capacity.',
                     content: { 'application/json': { schema: { $ref: '#/components/schemas/VisualiserFailedResponse' } } } },
            '504': { description: 'The agent did not reply within `VISUALISER_START_TIMEOUT_MS`.',
                     content: { 'application/json': { schema: { $ref: '#/components/schemas/VisualiserFailedResponse' } } } },
          },
        },
        get: {
          tags: ['Visualiser'],
          summary: 'List visualiser runs',
          description: 'Returns recent runs (newest first). Admin SPA polls this for the Visualiser page.',
          parameters: [
            { in: 'query', name: 'status', schema: { type: 'string' }, description: 'CSV of statuses to include (e.g. `streaming,importing,queued`).' },
            { in: 'query', name: 'limit',  schema: { type: 'integer', minimum: 1, maximum: 500, default: 50 } },
            { in: 'query', name: 'offset', schema: { type: 'integer', minimum: 0, default: 0 } },
          ],
          responses: {
            '200': {
              description: 'Page of runs.',
              content: { 'application/json': { schema: {
                type: 'object',
                properties: {
                  runs:   { type: 'array', items: { $ref: '#/components/schemas/VisualiserRun' } },
                  limit:  { type: 'integer' },
                  offset: { type: 'integer' },
                },
              } } },
            },
            '401': { $ref: '#/components/responses/Unauthorized' },
          },
        },
      },

      '/api/visualiser/streams/{runId}': {
        servers: [{ url: API_BASE }],
        get: {
          tags: ['Visualiser'],
          summary: 'Poll a visualiser run',
          parameters: [{ in: 'path', name: 'runId', required: true, schema: { type: 'string', format: 'uuid' } }],
          responses: {
            '200': { description: 'Current run state.', content: { 'application/json': { schema: { $ref: '#/components/schemas/VisualiserRun' } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '404': { $ref: '#/components/responses/NotFound' },
          },
        },
        delete: {
          tags: ['Visualiser'],
          summary: 'Stop a visualiser run',
          description: 'Sends `cancelVisualisation` to the agent (best-effort) and marks the row `ended`. The caller must be either the API key that started the run (matched by `requested_by_api_key_id`) or an admin session.',
          parameters: [{ in: 'path', name: 'runId', required: true, schema: { type: 'string', format: 'uuid' } }],
          responses: {
            '200': { description: 'Cancelled.', content: { 'application/json': { schema: { type: 'object', properties: { ok: { type: 'boolean', example: true } } } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '403': { description: 'Caller does not own the run.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '404': { $ref: '#/components/responses/NotFound' },
            '409': { description: 'Run is already terminal.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          },
        },
      },

      '/api/visualiser/streams/{runId}/signalling-token': {
        servers: [{ url: API_BASE }],
        post: {
          tags: ['Visualiser'],
          summary: 'Mint a signalling WS token',
          description: 'Returns a short-lived HS256 JWT (default TTL 5 minutes) the browser appends as `?token=…` to the signalling WS URL. The same ownership check as DELETE applies.',
          parameters: [{ in: 'path', name: 'runId', required: true, schema: { type: 'string', format: 'uuid' } }],
          responses: {
            '200': { description: 'Token minted.', content: { 'application/json': { schema: { $ref: '#/components/schemas/VisualiserSignallingToken' } } } },
            '401': { $ref: '#/components/responses/Unauthorized' },
            '403': { description: 'Caller does not own the run.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '404': { $ref: '#/components/responses/NotFound' },
            '409': { description: 'Run is not in `streaming` / `importing` state.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
            '503': { description: '`JWT_SIGNALLING_SECRET` is not configured.', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          },
        },
      },

      '/api/visualiser/workstations': {
        servers: [{ url: API_BASE }],
        get: {
          tags: ['Visualiser'],
          summary: 'List visualiser-capable workstations (admin only)',
          description: 'Drives the admin UI "Start new stream" dropdown.',
          responses: {
            '200': {
              description: 'OK.',
              content: { 'application/json': { schema: {
                type: 'object',
                properties: {
                  workstations: { type: 'array', items: {
                    type: 'object',
                    properties: {
                      id:                    { type: 'string', format: 'uuid' },
                      nodeName:              { type: 'string' },
                      machineId:             { type: 'string' },
                      canVisualise:          { type: 'boolean' },
                      currentVisualiserLoad: { type: 'integer' },
                      slotsTotal:            { type: 'integer' },
                      agentVersion:          { type: 'string', nullable: true },
                      online:                { type: 'boolean' },
                    },
                  } },
                },
              } } },
            },
            '401': { $ref: '#/components/responses/Unauthorized' },
          },
        },
      },
    },
  };
}
